### PR TITLE
 updated dccpi setup to switch from python2.7 to python 3.8

### PR DESCRIPTION
**Pull request by samFabrice**
I made an update of the version of python used by dccpi from python2.7 to python3.7 / python3.8

### CODE REVIEW

**Comment by hsanjuan** [comment]
These are just classifiers for pypi. Is there any code incompatibly that makes it not work with Python 3.8?

**Comment by samFabrice** [comment]
No.  it is precisely because I tested it with python 3.7 and the dccpi API
works that I thought it would be good to update its setup from python2.7 to
python3.7.

In the API that I did and uses DCCPI, I use the pint library that exists
only in Python3.7 what makes it clear from DCCPI I could not use mine

Le ven. 12 févr. 2021 à 18:21, Hector Sanjuan <notifications@github.com> a
écrit :

**Comment by hsanjuan** [comment]
setup.py says that it works with Python2.7 and Python 3, which should mean any Python3 version, including 3.7. But it also works with 2.7 still so no need to remove that.

**Comment by samFabrice** [comment]
Ok.  I understood.  thank you for your help

Le ven. 12 févr. 2021 à 20:10, Hector Sanjuan <notifications@github.com> a
écrit :

**Pull request closed without merging**
